### ISSUE TITLE
Dev UI is disabled forever after choosing prod in meilisearch-setup

### ISSUE THREAD

**Issue by drougojrom** [meilisearch/cloud-scripts#30]
I run `meilisearch-setup` second time after set up on digital ocean and expect that chosing `n` option should switch the environment to the development allowing the access to the UI. At the moment it does not. 

**To Reproduce**
1. setup using digital ocean [described here](https://docs.meilisearch.com/create/how_to/digitalocean_droplet.html#configure-production-settings-in-your-meilisearch-droplet)
2. run `meilisearch-setup` and choose production option 
3. run `meilisearch-setup` again and choose dev option
4. the UI is not available

**Expected behavior**
UI should be available

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: firefox, safari

**Comment by curquiza** [comment]
Hello @drougojrom!
Thanks for your report! I've just transferred the issue in the right repo so that our dev can fix it next week

**Comment by eskombro** [comment]
Hi @drougojrom 

Thanks for reporting this problem to us! This problem has been fixed and will be solved in the new MeilISearch releases.

If you want a workaround to solve this problem in your instance without any need or reinstalling or reindexing anything, you can connect to your instance via ssh (`ssh meilisearch@<your-instance-ip>`) and run the following commands:

```bash
curl -o /var/opt/meilisearch/scripts/first-login/000-set-meili-env.sh https://raw.githubusercontent.com/meilisearch/cloud-scripts/v0.19.0/scripts/first-login/000-set-meili-env.sh
curl -o /var/opt/meilisearch/scripts/first-login/001-setup-prod.sh https://raw.githubusercontent.com/meilisearch/cloud-scripts/v0.19.0/scripts/first-login/001-setup-prod.sh
meilisearch-setup
```

This time the script will work as expected!
