### ISSUE TITLE
Remove or specify analytics for CI/tests in cloud-repositories

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/cloud-scripts#44]
When launching the CI tests or testing in `meilisearch-digitalocean`, `meilisearch-aws` or `meilisearch-gcp`, the MeiliSearch instances that are launched either when creating the image or testing it has analytics specifying the provider.

It would be nice if we could disable the analytics while doing the CI/tests or specify that it comes from the CI/tests (for CI/tests monitoring for example).

The MeiliSearch configuration is located at `cloud-scripts/providers/{provider}/cloud-config.yaml`

The analytics and the `MEILI_SERVER_PROVIDER` still need to be set when creating the final image that will be released, because that's the MeiliSearch that will be used by future users.

**Comment by alallema** [comment]
Closing this issue due to the depreciation of this repository
