### ISSUE TITLE
Change digital ocean image naming to include rc number

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/cloud-scripts#53]
When generating a digital ocean image the naming looks like this: 

```
MeiliSearch-v0.22.0-rc-Debian-10.3
```

Since there is no `rc` number we have to remember which rc image it is and delete it to create the more recent rc's. 

This may lead to images with the wrong `rc` without us knowing.

**Comment by alallema** [comment]
Even if it could be useful it is not the case for the use of this repo. The RC images are only used for pre-release testing and are not intended to remain on Digital Ocean.
See with @curquiza I'm closing this issue🙂
