### ISSUE TITLE
Undefined path for the dumps/ folder

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/cloud-scripts#55]
Currently, when creating a dump, the dumps folder path is undefined and depends on the system meilisearch is running. `systemd` seems to create it at the root, but when we run meilisearch on a local machine it's in the same directory as MeiliSearch binary. The dumps folder path should be defined by an env variable in the service, and should be consistent among different services :)

**Comment by alallema** [comment]
Hi @CaroFG,
Thanks for raising this issue. Normally the dumps folder is always created at the root of the machine `/dumps` to be easily found on all the different systems. But we can add an option on the `meilisearch-setup` to choose a specific folder and also add this information to the documentation.

**Comment by CaroFG** [comment]
I see. The [documentation ](https://docs.meilisearch.com/reference/features/dumps.html#creating-a-dump)states: "By default, this folder is /dumps at the root of your MeiliSearch binary, but this can be customized." And that is true when you install meilisearch locally. So users are getting confused and are having a hard time finding the dumps in droplets, etc. IDK what would be the best solution to solve this

**Comment by alallema** [comment]
You right. After discussion with the integration team, the folder `dumps` would be created in  `/var/opt/meilisearch`.

**Comment by alallema** [comment]
To do:
- New path `/var/opt/meilisearch`
- ⚠️ this will be available only for MeiliSearch v0.23.0
- I will open an issue on the documentation when this issue is solved.
